apiVersion: v1
kind: Namespace
metadata:
  name: dynatrace-counters
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-counters
  namespace: dynatrace-counters
  labels:
    app: dynatrace-counters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynatrace-counters
  template:
    metadata:
      labels:
        app: dynatrace-counters
      annotations:
        sidecar.istio.io/inject: "false" # disable istio for scraping
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      automountServiceAccountToken: false
      containers:
        - name: dynatrace-counters
          image: matthiaswinzeler/dynatrace-counters
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: dynatrace-counters
  namespace: dynatrace-counters
  labels:
    app: dynatrace-counters
  annotations:
    metrics.dynatrace.com/scrape: 'true'
    metrics.dynatrace.com/path: '/metrics'
spec:
  selector:
    app: dynatrace-counters
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 8090